In [3]:
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [4]:
file_path = '/Users/johnsonwei/Desktop/Blockhouse/Jefferies/UST Data Sample (July - Sept 2024).xlsx'
df = pd.read_excel(file_path)

# Data Information

In [5]:
df.columns

Index(['let me tak', 'Id', 'Client', 'RFQStatus', 'InstrumentSubGroup',
       'Market Traded Vol (USD)', 'Our Traded Vol', 'TiedWonVol',
       'Num of Dealers', 'Trader', 'Sales', 'Covered Vol', 'ActionStr', 'Tier',
       'InstrumentCode', 'InstrumentDescription', 'AssetClass', 'Market',
       'LegNo', 'Maturity Date', 'RFQNumberOfQuotes', 'Buy/Sell',
       'Best Bid Price', 'Mid Price', 'Best Ask Price', 'Deal Value',
       'AwayFromMid', 'TickIdentifier', 'Deal Spread', 'Cover', 'CoverPnL',
       'SettlementDays', 'SettlementDate', 'SettlementStops', 'RFQ CreateTime',
       'RFQ ClosedTime', 'AnAutoReplyRFQs', 'First Response Time (Sec)',
       'TradeSizeBucket', 'Sector', 'MaturityBucket'],
      dtype='object')

In [6]:
len(df)

66681

In [7]:
df.head(10)

,let me tak,Id,Client,RFQStatus,InstrumentSubGroup,Market Traded Vol (USD),Our Traded Vol,TiedWonVol,Num of Dealers,Trader,...,SettlementDays,SettlementDate,SettlementStops,RFQ CreateTime,RFQ ClosedTime,AnAutoReplyRFQs,First Response Time (Sec),TradeSizeBucket,Sector,MaturityBucket
0,2024-09-30,66FA7D45432800D20002,Client1,Done,OFFTHERUN,100000000,100000000,100000000,6,Trader1,...,1,2024-10-01,T+1,2024-09-30 06:28:00,2024-09-30 06:28:00,1,0.03,50+M,5-7 YR,5y-7y
1,2024-09-30,TRSY_20240930_15961,Client2,Done,"OFFTHERUN,DOUBLEOLDS",2100000,2100000,2100000,5,Trader2,...,1,2024-10-01,T+1,2024-09-30 16:00:00,2024-09-30 16:00:00,1,0.95,1-5M,7-10 YR,7y-10y
2,2024-09-30,TRSY_20240930_314,Client2,Done,ONTHERUN,53000000,53000000,53000000,5,Trader3,...,1,2024-10-01,T+1,2024-09-30 15:46:00,2024-09-30 15:46:00,1,0.07,50+M,7-10 YR,7y-10y
3,2024-09-30,66FAEA57432800020001,Client3,Done,OFFTHERUN,500000,500000,500000,5,Trader4,...,1,2024-10-01,T+1,2024-09-30 14:14:00,2024-09-30 14:14:00,1,0.03,500K-1M,0-1 YR,<18mos
4,2024-09-30,66FAC35D455C00210006,Client4,Done,OFFTHERUN,1058000,1058000,1058000,5,Trader2,...,1,2024-10-01,T+1,2024-09-30 11:27:00,2024-09-30 11:27:00,1,0.03,1-5M,5-7 YR,3y-5y
5,2024-09-30,66FB01C6432800130001,Client4,Done,ONTHERUN,25000000,25000000,0,5,Trader4,...,1,2024-10-01,T+1,2024-09-30 15:53:00,2024-09-30 15:54:00,0,13.28,25-50M,BILLS,<18mos
6,2024-09-30,66FAFF05432800000001,Client5,Done,ONTHERUN,1132000,1132000,0,1,Trader2,...,1,2024-10-01,T+1,2024-09-30 15:42:00,2024-09-30 15:42:00,1,0.03,1-5M,5-7 YR,5y-7y
7,2024-09-30,66FAEFC145C4000A0001,Client5,Done,ONTHERUN,818000,818000,0,1,Trader2,...,1,2024-10-01,T+1,2024-09-30 14:36:00,2024-09-30 14:36:00,1,0.03,500K-1M,7-10 YR,7y-10y
8,2024-09-30,66FA9F0D45C400400001,Client5,Done,ONTHERUN,500000,500000,0,1,Trader2,...,1,2024-10-01,T+1,2024-09-30 08:53:00,2024-09-30 08:53:00,1,0.03,500K-1M,3-5 YR,3y-5y
9,2024-09-30,66FB0D0C45C400000001,Client5,Done,ONTHERUN,500000,500000,500000,5,Trader2,...,1,2024-10-01,T+1,2024-09-30 16:41:00,2024-09-30 16:41:00,1,0.04,500K-1M,7-10 YR,7y-10y

In [8]:
df.describe()

,let me tak,Market Traded Vol (USD),Our Traded Vol,TiedWonVol,Num of Dealers,Covered Vol,LegNo,Maturity Date,RFQNumberOfQuotes,Best Bid Price,...,Deal Value,AwayFromMid,Deal Spread,Cover,SettlementDays,SettlementDate,RFQ CreateTime,RFQ ClosedTime,AnAutoReplyRFQs,First Response Time (Sec)
count,66681,6.668100e+04,6.668100e+04,6.668100e+04,66681.000000,6.668100e+04,66681.000000,66681,66681.000000,66681.000000,...,66681.000000,6.668100e+04,66681.000000,66681.000000,66681.000000,66681,66681,66681,66681.000000,66681.000000
mean,2024-08-16 21:24:50.241598208,9.103470e+06,1.302165e+06,1.783406e+05,6.112476,1.664401e+06,0.017756,1997-09-29 08:14:00.923201664,4.417180,62.295291,...,-71.022155,1.655243e+05,0.080674,1.951735,1.050989,2024-08-18 08:40:50.209205248,2024-08-17 08:42:32.188779264,2024-08-17 08:42:42.610338816,0.640242,1.140302
min,2024-07-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,0.000000,1930-01-15 00:00:00,0.000000,0.000000,...,-999999.000000,0.000000e+00,-531.980000,-45.300000,0.000000,2024-07-01 00:00:00,2024-07-01 04:01:00,2024-07-01 04:01:00,0.000000,0.000000
25%,2024-07-25 00:00:00,6.000000e+05,0.000000e+00,0.000000e+00,4.000000,0.000000e+00,0.000000,1951-11-15 00:00:00,1.000000,5.140000,...,5.150000,1.280000e+00,0.000000,0.000000,1.000000,2024-07-26 00:00:00,2024-07-25 13:18:00,2024-07-25 13:18:00,0.000000,0.020000
50%,2024-08-16 00:00:00,1.500000e+06,0.000000e+00,0.000000e+00,5.000000,0.000000e+00,0.000000,2024-10-22 00:00:00,2.000000,97.558594,...,98.050781,3.000000e+00,0.000000,0.000000,1.000000,2024-08-19 00:00:00,2024-08-16 08:35:00,2024-08-16 08:35:00,1.000000,0.030000
75%,2024-09-10 00:00:00,5.000000e+06,0.000000e+00,0.000000e+00,7.000000,0.000000e+00,0.000000,2025-07-10 00:00:00,4.000000,100.628906,...,100.687500,7.000000e+00,0.000000,0.000000,1.000000,2024-09-11 00:00:00,2024-09-10 12:01:00,2024-09-10 12:01:00,1.000000,0.050000
max,2024-09-30 00:00:00,1.486000e+09,9.000000e+08,5.000000e+08,22.000000,6.750000e+08,2.000000,2029-12-31 00:00:00,90.000000,114.351562,...,999999.000000,2.559997e+08,458.440000,113.832031,10.000000,2024-10-04 00:00:00,2024-09-30 16:58:00,2024-09-30 16:58:00,1.000000,109.090000
std,NaN,3.280953e+07,1.424713e+07,4.730946e+06,4.085569,1.366841e+07,0.138170,NaN,8.314328,46.111660,...,25394.307745,6.498830e+06,12.307430,13.714968,0.579735,NaN,NaN,NaN,0.479933,3.747233

In [9]:
missing_values = df.isnull().sum()
missing_values

let me tak                     0
Id                             0
Client                         0
RFQStatus                      0
InstrumentSubGroup             0
Market Traded Vol (USD)        0
Our Traded Vol                 0
TiedWonVol                     0
Num of Dealers                 0
Trader                         0
Sales                          0
Covered Vol                    0
ActionStr                      0
Tier                           0
InstrumentCode                 0
InstrumentDescription          0
AssetClass                     0
Market                         0
LegNo                          0
Maturity Date                  0
RFQNumberOfQuotes              0
Buy/Sell                       0
Best Bid Price                 0
Mid Price                      0
Best Ask Price                 0
Deal Value                     0
AwayFromMid                    0
TickIdentifier               445
Deal Spread                    0
Cover                          0
CoverPnL                       0
SettlementDays                 0
SettlementDate                 0
SettlementStops                0
RFQ CreateTime                 0
RFQ ClosedTime                 0
AnAutoReplyRFQs                0
First Response Time (Sec)      0
TradeSizeBucket                0
Sector                         0
MaturityBucket                 0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
len(df['Client'].unique())

928

In [12]:
len(df['Trader'].unique())

9

In [13]:
# Count of "TFRNS"
tfrns_count = df[df['AssetClass'] == 'TFRNS'].shape[0]

print(f'Total number of TFRNS in AssetClass column: {tfrns_count}')

Total number of TFRNS in AssetClass column: 64

In [14]:
df = df[df['AssetClass'] != 'TFRNS']

In [15]:
df.head(80)

,let me tak,Id,Client,RFQStatus,InstrumentSubGroup,Market Traded Vol (USD),Our Traded Vol,TiedWonVol,Num of Dealers,Trader,...,SettlementDays,SettlementDate,SettlementStops,RFQ CreateTime,RFQ ClosedTime,AnAutoReplyRFQs,First Response Time (Sec),TradeSizeBucket,Sector,MaturityBucket
0,2024-09-30,66FA7D45432800D20002,Client1,Done,OFFTHERUN,100000000,100000000,100000000,6,Trader1,...,1,2024-10-01,T+1,2024-09-30 06:28:00,2024-09-30 06:28:00,1,0.03,50+M,5-7 YR,5y-7y
1,2024-09-30,TRSY_20240930_15961,Client2,Done,"OFFTHERUN,DOUBLEOLDS",2100000,2100000,2100000,5,Trader2,...,1,2024-10-01,T+1,2024-09-30 16:00:00,2024-09-30 16:00:00,1,0.95,1-5M,7-10 YR,7y-10y
2,2024-09-30,TRSY_20240930_314,Client2,Done,ONTHERUN,53000000,53000000,53000000,5,Trader3,...,1,2024-10-01,T+1,2024-09-30 15:46:00,2024-09-30 15:46:00,1,0.07,50+M,7-10 YR,7y-10y
3,2024-09-30,66FAEA57432800020001,Client3,Done,OFFTHERUN,500000,500000,500000,5,Trader4,...,1,2024-10-01,T+1,2024-09-30 14:14:00,2024-09-30 14:14:00,1,0.03,500K-1M,0-1 YR,<18mos
4,2024-09-30,66FAC35D455C00210006,Client4,Done,OFFTHERUN,1058000,1058000,1058000,5,Trader2,...,1,2024-10-01,T+1,2024-09-30 11:27:00,2024-09-30 11:27:00,1,0.03,1-5M,5-7 YR,3y-5y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2024-09-30,66FAF945483000150001,Client38,Done,ONTHERUN,24500000,24500000,0,5,Trader4,...,1,2024-10-01,T+1,2024-09-30 15:18:00,2024-09-30 15:18:00,0,4.50,10-25M,BILLS,<18mos
76,2024-09-30,66FAF8C9483000000001,Client38,Done,ONTHERUN,24500000,24500000,0,5,Trader4,...,1,2024-10-01,T+1,2024-09-30 15:16:00,2024-09-30 15:16:00,0,5.15,10-25M,BILLS,<18mos
77,2024-09-30,TRSY_20240930_1427,Client39,Done,"OFFTHERUN,OLDBONDS",5620000,5620000,0,1,Trader3,...,1,2024-10-01,T+1,2024-09-30 11:27:00,2024-09-30 11:27:00,0,0.06,5-10M,15-30 YR,10-30y
78,2024-09-30,TRSY_20240930_3079,Client39,Done,"OFFTHERUN,OLDBONDS",1810000,1810000,0,1,Trader2,...,1,2024-10-01,T+1,2024-09-30 09:05:00,2024-09-30 09:05:00,0,0.06,1-5M,15-30 YR,10-30y
79,2024-09-30,TRSY_20240930_1065,Client39,Done,ONTHERUN,4280000,4280000,0,1,Trader2,...,1,2024-10-01,T+1,2024-09-30 15:53:00,2024-09-30 15:53:00,0,0.05,1-5M,7-10 YR,7y-10y

In [16]:
def convert_year(row):
    year = row.year  # Extract the year
    month = row.month  # Extract the month
    day = row.day  # Extract the day
    if year < 2000:
        year += 100  # Convert 19xx to 20xx
    return pd.Timestamp(year=year, month=month, day=day)

# Apply the conversion function to the 'Maturity Date' column
df['Maturity Date'] = df['Maturity Date'].apply(convert_year)

# Print the updated DataFrame
print(df)

      let me tak                    Id     Client        RFQStatus  \
0     2024-09-30  66FA7D45432800D20002    Client1             Done
1     2024-09-30   TRSY_20240930_15961    Client2             Done
2     2024-09-30     TRSY_20240930_314    Client2             Done
3     2024-09-30  66FAEA57432800020001    Client3             Done
4     2024-09-30  66FAC35D455C00210006    Client4             Done
...          ...                   ...        ...              ...
66676 2024-07-01  E68302E5454C00010001   Client33  CustomerTimeOut
66677 2024-07-01  E68305CA57D000080001   Client33  CustomerTimeOut
66678 2024-07-01  E683099657D000010001   Client33  CustomerTimeOut
66679 2024-07-01  6682BE1857D0000C0002  Client271  CustomerTimeOut
66680 2024-07-01  6682D14445CC00050001   Client38  CustomerTimeOut

         InstrumentSubGroup  Market Traded Vol (USD)  Our Traded Vol  \
0                 OFFTHERUN                100000000       100000000
1      OFFTHERUN,DOUBLEOLDS                  2100000         2100000
2                  ONTHERUN                 53000000        53000000
3                 OFFTHERUN                   500000          500000
4                 OFFTHERUN                  1058000         1058000
...                     ...                      ...             ...
66676              ONTHERUN                        0               0
66677              ONTHERUN                        0               0
66678              ONTHERUN                        0               0
66679             OFFTHERUN                        0               0
66680             OFFTHERUN                        0               0

       TiedWonVol  Num of Dealers   Trader  ... SettlementDays  \
0       100000000               6  Trader1  ...              1
1         2100000               5  Trader2  ...              1
2        53000000               5  Trader3  ...              1
3          500000               5  Trader4  ...              1
4         1058000               5  Trader2  ...              1
...           ...             ...      ...  ...            ...
66676           0               1  Trader4  ...              1
66677           0               1  Trader4  ...              1
66678           0               1  Trader4  ...              1
66679           0              15  Trader4  ...              1
66680           0               5  Trader4  ...              0

       SettlementDate SettlementStops      RFQ CreateTime      RFQ ClosedTime  \
0          2024-10-01             T+1 2024-09-30 06:28:00 2024-09-30 06:28:00
1          2024-10-01             T+1 2024-09-30 16:00:00 2024-09-30 16:00:00
2          2024-10-01             T+1 2024-09-30 15:46:00 2024-09-30 15:46:00
3          2024-10-01             T+1 2024-09-30 14:14:00 2024-09-30 14:14:00
4          2024-10-01             T+1 2024-09-30 11:27:00 2024-09-30 11:27:00
...               ...             ...                 ...                 ...
66676      2024-07-02             T+1 2024-07-01 15:26:00 2024-07-01 15:27:00
66677      2024-07-02             T+1 2024-07-01 15:38:00 2024-07-01 15:40:00
66678      2024-07-02             T+1 2024-07-01 15:55:00 2024-07-01 15:56:00
66679      2024-07-02             T+1 2024-07-01 10:33:00 2024-07-01 10:34:00
66680      2024-07-01             T+0 2024-07-01 11:56:00 2024-07-01 11:57:00

      AnAutoReplyRFQs First Response Time (Sec) TradeSizeBucket   Sector  \
0                   1                      0.03            50+M   5-7 YR
1                   1                      0.95            1-5M  7-10 YR
2                   1                      0.07            50+M  7-10 YR
3                   1                      0.03         500K-1M   0-1 YR
4                   1                      0.03            1-5M   5-7 YR
...               ...                       ...             ...      ...
66676               1                      0.04            1-5M    BILLS
66677               1                      0.04            1-5M    BILLS
66678               1                      0.04            1-5M    BILLS
66679               0                      4.99          10-25M   0-1 YR
66680               0                      7.60            1-5M    BILLS

      MaturityBucket
0              5y-7y
1             7y-10y
2             7y-10y
3             <18mos
4              3y-5y
...              ...
66676         <18mos
66677         <18mos
66678         <18mos
66679         <18mos
66680         <18mos

[66172 rows x 41 columns]

In [17]:
df['Maturity Date'].unique()

<DatetimeArray>
['2030-04-30 00:00:00', '2034-02-15 00:00:00', '2031-09-30 00:00:00',
 '2025-09-15 00:00:00', '2028-06-30 00:00:00', '2024-10-29 00:00:00',
 '2029-09-30 00:00:00', '2027-09-15 00:00:00', '2034-08-15 00:00:00',
 '2044-08-15 00:00:00',
 ...
 '2034-11-15 00:00:00', '2024-07-23 00:00:00', '2024-07-18 00:00:00',
 '2037-08-15 00:00:00', '2024-07-16 00:00:00', '2024-07-15 00:00:00',
 '2024-07-11 00:00:00', '2024-07-09 00:00:00', '2024-07-05 00:00:00',
 '2024-07-02 00:00:00']
Length: 319, dtype: datetime64[ns]

In [18]:
# Function to calculate years to maturity
def calculate_years_to_maturity(row):
    maturity_date = pd.to_datetime(row['Maturity Date'])
    trade_date = pd.to_datetime(row['let me tak'])
    return (maturity_date - trade_date).days / 365.25

df['Years to Maturity'] = df.apply(calculate_years_to_maturity, axis=1)


def extract_yield(description):
    match = re.search(r"(\d+\.\d+)", description)
    return float(match.group(1)) if match else np.nan  # Return NaN if no match is found

df['Yield'] = df['InstrumentDescription'].apply(extract_yield)

def yield_to_price(ytm, years_to_maturity, face_value=100):
    if pd.isna(ytm) or pd.isna(years_to_maturity):
        return np.nan
    return face_value / ((1 + 0.01 * ytm) ** years_to_maturity)

def bill_price(face_value, deal_price, days_to_maturity):
    if pd.isna(deal_price) or pd.isna(days_to_maturity):
        return np.nan
    discount_yield = ((face_value - deal_price) / face_value) * (360 / days_to_maturity)
    return face_value * (1 - (discount_yield / 100) * (days_to_maturity / 360))

# Columns to convert
columns_to_convert = ['Best Bid Price', 'Mid Price', 'Best Ask Price', 'Deal Value', 'Cover']

for column in columns_to_convert:
    df[f'Converted {column}'] = df.apply(
        lambda row: (
            # yield_to_price(row['Yield'], row['Years to Maturity']) if row['AssetClass'] == 'STRIPS'
            # else (
                bill_price(100, row[column], (pd.to_datetime(row['Maturity Date']) - pd.to_datetime(row['let me tak'])).days)
                if (row['AssetClass'] == 'BILLS' or row['AssetClass'] == 'STRIPS')else row[column]
            # )
        ),
        axis=1
    )

print(df[['InstrumentDescription', 'AssetClass', 'Yield', 'Years to Maturity'] + [f'Converted {col}' for col in columns_to_convert]])

        InstrumentDescription AssetClass  Yield  Years to Maturity  \
0           T  3.500 04/30/30      BONDS  3.500           5.579740
1           T  4.000 02/15/34      BONDS  4.000           9.377139
2      T  3.625 09/30/31  7YR      BONDS  3.625           6.997947
3           T  3.500 09/15/25      BONDS  3.500           0.958248
4           T  4.000 06/30/28      BONDS  4.000           3.748118
...                       ...        ...    ...                ...
66676        B  09/26/24  3MO      BILLS    NaN           0.238193
66677        B  09/26/24  3MO      BILLS    NaN           0.238193
66678        B  09/26/24  3MO      BILLS    NaN           0.238193
66679       T  1.000 12/15/24      BONDS  1.000           0.457221
66680             B  07/02/24      BILLS    NaN           0.002738

       Converted Best Bid Price  Converted Mid Price  \
0                     99.539062            99.550781
1                    101.712388           101.724107
2                     99.761719            99.765625
3                     99.535156            99.539062
4                    101.601562           101.609375
...                         ...                  ...
66676                 99.052250            99.052225
66677                 99.052250            99.052225
66678                 99.052250            99.052225
66679                 98.085938            98.095703
66680                 99.052700            99.052450

       Converted Best Ask Price  Converted Deal Value  Converted Cover
0                     99.562500             99.558594        99.558594
1                    101.735826            101.726562       101.726562
2                     99.769531             99.761719        99.761719
3                     99.542969             99.554688        99.554688
4                    101.617188            101.605469       101.605469
...                         ...                   ...              ...
66676                 99.052200             99.052175        99.000000
66677                 99.052200             99.052175        99.000000
66678                 99.052200             99.052175        99.000000
66679                 98.105469             98.132812         0.000000
66680                 99.052200             99.053500        99.000000

[66172 rows x 9 columns]

In [19]:
# Filter the DataFrame for AssetClass that is either BILLS or STRIPS
bills_strips_df = df[df['AssetClass'].isin(['BILLS', 'STRIPS', 'BONDS'])]

# Select only the columns that are related to converted prices
columns_to_display = ['InstrumentDescription', 'AssetClass', 'Yield', 'Years to Maturity'] + [f'Converted {col}' for col in columns_to_convert]

# Display the filtered DataFrame with the desired columns
print(bills_strips_df[columns_to_display].head(30))

      InstrumentDescription AssetClass  Yield  Years to Maturity  \
0         T  3.500 04/30/30      BONDS  3.500           5.579740
1         T  4.000 02/15/34      BONDS  4.000           9.377139
2    T  3.625 09/30/31  7YR      BONDS  3.625           6.997947
3         T  3.500 09/15/25      BONDS  3.500           0.958248
4         T  4.000 06/30/28      BONDS  4.000           3.748118
5          B  10/29/24  1MO      BILLS    NaN           0.079398
6    T  3.500 09/30/29  5YR      BONDS  3.500           4.999316
7    T  3.625 09/30/31  7YR      BONDS  3.625           6.997947
8    T  3.375 09/15/27  3YR      BONDS  3.375           2.956879
9   T  3.875 08/15/34  10YR      BONDS  3.875           9.872690
10   T  3.500 09/30/29  5YR      BONDS  3.500           4.999316
11  T  4.125 08/15/44  20YR      BONDS  4.125          19.874059
12  T  3.875 08/15/34  10YR      BONDS  3.875           9.872690
13  T  4.250 08/15/54  30YR      BONDS  4.250          29.872690
14  T  3.875 08/15/34  10YR      BONDS  3.875           9.872690
15         B  10/29/24  1MO      BILLS    NaN           0.079398
16              B  08/07/25      BILLS    NaN           0.851472
17        T  1.625 02/15/26      BONDS  1.625           1.377139
18   T  3.625 09/30/31  7YR      BONDS  3.625           6.997947
19   T  3.625 09/30/31  7YR      BONDS  3.625           6.997947
20   T  3.500 09/30/29  5YR      BONDS  3.500           4.999316
21        T  1.625 05/15/31      BONDS  1.625           6.620123
22              B  01/14/25      BILLS    NaN           0.290212
23        T  4.375 05/15/34      BONDS  4.375           9.620808
24  T  3.875 08/15/34  10YR      BONDS  3.875           9.872690
25        T  3.250 06/30/29      BONDS  3.250           4.747433
26        T  3.625 08/31/29      BONDS  3.625           4.917180
27  T  3.875 08/15/34  10YR      BONDS  3.875           9.872690
28   T  3.500 09/30/29  5YR      BONDS  3.500           4.999316
29  T  3.875 08/15/34  10YR      BONDS  3.875           9.872690

    Converted Best Bid Price  Converted Mid Price  Converted Best Ask Price  \
0                  99.539062            99.550781                 99.562500
1                 101.712388           101.724107                101.735826
2                  99.761719            99.765625                 99.769531
3                  99.535156            99.539062                 99.542969
4                 101.601562           101.609375                101.617188
5                  99.047425            99.047400                 99.047375
6                  99.640625            99.644531                 99.648438
7                  99.726562            99.730469                 99.734375
8                  99.546875            99.548828                 99.550781
9                 100.738281           100.742188                100.746094
10                 99.640625            99.642578                 99.644531
11                  0.000000             0.000000                  0.000000
12                100.710938           100.714844                100.718750
13                  0.000000             0.000000                  0.000000
14                100.804688           100.808594                100.812500
15                 99.047150            99.047125                 99.047100
16                 99.038500            99.038450                 99.038400
17                 97.167969            97.191406                 97.214844
18                 99.710938            99.714844                 99.718750
19                 99.984375            99.988281                 99.992188
20                 99.882812            99.886719                 99.890625
21                 88.281250            88.296875                 88.312500
22                 99.044500            99.044450                 99.044400
23                104.771748           104.783467                104.795185
24                  0.000000             0.000000                  0.000000
25                 98.722656            98.738281                 98.753906
26                100.500000           100.503906                100.507812
27                100.585938           100.589844                100.593750
28                 99.863281            99.867188                 99.871094
29                100.875000           100.878906                100.882812

    Converted Deal Value  Converted Cover
0              99.558594        99.558594
1             101.726562       101.726562
2              99.761719        99.761719
3              99.554688        99.554688
4             101.605469       101.605469
5              99.047345        99.047310
6              99.640625         0.000000
7              99.734375         0.000000
8              99.546875         0.000000
9             100.738281       100.738281
10             99.644531        99.644531
11             99.238281       -45.300000
12            100.726562       -45.300000
13            102.140625       -45.300000
14            100.796875         3.900000
15             99.046950        99.000000
16             99.038405        99.038400
17             97.207031        97.210938
18             99.710938         0.000000
19             99.984375         0.000000
20             99.882812         0.000000
21             88.289062        88.285156
22             99.044350        99.000000
23            105.546875       104.957031
24            101.500000       100.914062
25             98.746094        98.746094
26            100.500000       100.500000
27            100.589844       100.589844
28             99.863281         0.000000
29            100.875000         0.000000

In [20]:
df.columns

Index(['let me tak', 'Id', 'Client', 'RFQStatus', 'InstrumentSubGroup',
       'Market Traded Vol (USD)', 'Our Traded Vol', 'TiedWonVol',
       'Num of Dealers', 'Trader', 'Sales', 'Covered Vol', 'ActionStr', 'Tier',
       'InstrumentCode', 'InstrumentDescription', 'AssetClass', 'Market',
       'LegNo', 'Maturity Date', 'RFQNumberOfQuotes', 'Buy/Sell',
       'Best Bid Price', 'Mid Price', 'Best Ask Price', 'Deal Value',
       'AwayFromMid', 'TickIdentifier', 'Deal Spread', 'Cover', 'CoverPnL',
       'SettlementDays', 'SettlementDate', 'SettlementStops', 'RFQ CreateTime',
       'RFQ ClosedTime', 'AnAutoReplyRFQs', 'First Response Time (Sec)',
       'TradeSizeBucket', 'Sector', 'MaturityBucket', 'Years to Maturity',
       'Yield', 'Converted Best Bid Price', 'Converted Mid Price',
       'Converted Best Ask Price', 'Converted Deal Value', 'Converted Cover'],
      dtype='object')

In [21]:
def calculate_slippage_price(row):
    if row['Buy/Sell'] == 'Buy':
        return (row['Converted Deal Value'] - row['Converted Mid Price'])
    elif row['Buy/Sell'] == 'Sell':
        return (row['Converted Mid Price'] - row['Converted Deal Value'])
    return None

df['Slippage'] = df.apply(calculate_slippage_price, axis=1)

df=df[df['Converted Best Ask Price']!=0.0]
df=df[df['Converted Mid Price']!=0.0]
df=df[df['Converted Deal Value']!=0.0]

In [22]:
df=df.dropna()

In [23]:
df['Spread'] = df['Converted Best Ask Price'] - df['Converted Best Bid Price']

In [24]:
buy=df[df['Buy/Sell']=="Buy"]
sell=df[df['Buy/Sell']=='Sell']

buygroup=buy.groupby(['InstrumentSubGroup',"Tier"])['Slippage'].mean().sort_values(ascending=False)
sellgroup=sell.groupby(['InstrumentSubGroup',"Tier"])['Slippage'].mean().sort_values(ascending=False)

print(buygroup[:5])
print(buygroup[-5:])
print(sellgroup[:5])
print(sellgroup[-5:])

InstrumentSubGroup    Tier
UNKNOWN               MANUAL      0.003071
                      TIER2       0.002085
                      TIER9       0.002000
                      TIER1       0.001000
OFFTHERUN,DOUBLEOLDS  TierGOLD   -0.003358
Name: Slippage, dtype: float64
InstrumentSubGroup    Tier
OFFTHERUN             TIER2     -0.030002
                      MANUAL    -0.030439
OFFTHERUN,DOUBLEOLDS  TIER3     -0.035156
OFFTHERUN             UNKNOWN   -0.058350
ONTHERUN              TIER1     -1.095957
Name: Slippage, dtype: float64
InstrumentSubGroup  Tier
ONTHERUN            TierGOLD    0.003551
UNKNOWN             TIER1       0.002500
                    MANUAL      0.001463
                    TIER2       0.001250
                    TIER9       0.000375
Name: Slippage, dtype: float64
InstrumentSubGroup    Tier
OFFTHERUN             TIER1     -0.029746
OFFTHERUN,OLDBONDS    TIER9     -0.037133
OFFTHERUN             UNKNOWN   -0.039453
OFFTHERUN,DOUBLEOLDS  TIER9     -0.049070
OFFTHERUN             TIER3     -0.101562
Name: Slippage, dtype: float64

In [25]:
# Creating DataFrames based on the updated values provided
data_1 = {
    "InstrumentSubGroup": ["UNKNOWN", "UNKNOWN", "UNKNOWN", "UNKNOWN", "OFFTHERUN,DOUBLEOLDS"],
    "Tier": ["MANUAL", "TIER2", "TIER9", "TIER1", "TierGOLD"],
    "slippege": [0.003071, 0.002085, 0.002000, 0.001000, -0.003358]
}

data_2 = {
    "InstrumentSubGroup": ["OFFTHERUN", "OFFTHERUN", "OFFTHERUN,DOUBLEOLDS", "OFFTHERUN", "ONTHERUN"],
    "Tier": ["TIER2", "MANUAL", "TIER3", "UNKNOWN", "TIER1"],
    "slippege": [-0.030002, -0.030439, -0.035156, -0.058350, -1.095957]
}

data_3 = {
    "InstrumentSubGroup": ["ONTHERUN", "UNKNOWN", "UNKNOWN", "UNKNOWN", "UNKNOWN"],
    "Tier": ["TierGOLD", "TIER1", "MANUAL", "TIER2", "TIER9"],
    "slippege": [0.003551, 0.002500, 0.001463, 0.001250, 0.000375]
}

data_4 = {
    "InstrumentSubGroup": ["OFFTHERUN", "OFFTHERUN,OLDBONDS", "OFFTHERUN", "OFFTHERUN,DOUBLEOLDS", "OFFTHERUN"],
    "Tier": ["TIER1", "TIER9", "UNKNOWN", "TIER9", "TIER3"],
    "slippege": [-0.029746, -0.037133, -0.039453, -0.049070, -0.101562]
}

# Create DataFrames
df1 = pd.DataFrame(data_1)
df2 = pd.DataFrame(data_2)
df3 = pd.DataFrame(data_3)
df4 = pd.DataFrame(data_4)

# Plotting the data
plt.figure(figsize=(15, 10))

# Plot positive and negative slippage from df1
plt.subplot(2, 2, 1)
plt.barh(df1["InstrumentSubGroup"] + ", " + df1["Tier"], df1["slippege"], color='green')
plt.title("Buy Slippage Top 5")
plt.xlabel("Slippage")
plt.ylabel("InstrumentSubGroup, Tier")

# Plot negative slippage from df2
plt.subplot(2, 2, 2)
plt.barh(df2["InstrumentSubGroup"] + ", " + df2["Tier"], df2["slippege"], color='red')
plt.title("Buy Slippage Bottom 5")
plt.xlabel("Slippage")
plt.ylabel("InstrumentSubGroup, Tier")

# Plot positive slippage from df3
plt.subplot(2, 2, 3)
plt.barh(df3["InstrumentSubGroup"] + ", " + df3["Tier"], df3["slippege"], color='blue')
plt.title("Sell Slippage Top 5")
plt.xlabel("Slippage")
plt.ylabel("InstrumentSubGroup, Tier")

# Plot negative slippage from df4
plt.subplot(2, 2, 4)
plt.barh(df4["InstrumentSubGroup"] + ", " + df4["Tier"], df4["slippege"], color='orange')
plt.title("Sell Slippage Bottom 5")
plt.xlabel("Slippage")
plt.ylabel("InstrumentSubGroup, Tier")

plt.tight_layout()
plt.show()

NameError: name 'plt' is not defined

In [27]:
df['timebetween']=df['RFQ ClosedTime']-df['RFQ CreateTime']

In [28]:
df['timebetween_minutes'] = df['timebetween'].dt.total_seconds() / 60

In [29]:
df.columns

Index(['let me tak', 'Id', 'Client', 'RFQStatus', 'InstrumentSubGroup',
       'Market Traded Vol (USD)', 'Our Traded Vol', 'TiedWonVol',
       'Num of Dealers', 'Trader', 'Sales', 'Covered Vol', 'ActionStr', 'Tier',
       'InstrumentCode', 'InstrumentDescription', 'AssetClass', 'Market',
       'LegNo', 'Maturity Date', 'RFQNumberOfQuotes', 'Buy/Sell',
       'Best Bid Price', 'Mid Price', 'Best Ask Price', 'Deal Value',
       'AwayFromMid', 'TickIdentifier', 'Deal Spread', 'Cover', 'CoverPnL',
       'SettlementDays', 'SettlementDate', 'SettlementStops', 'RFQ CreateTime',
       'RFQ ClosedTime', 'AnAutoReplyRFQs', 'First Response Time (Sec)',
       'TradeSizeBucket', 'Sector', 'MaturityBucket', 'Years to Maturity',
       'Yield', 'Converted Best Bid Price', 'Converted Mid Price',
       'Converted Best Ask Price', 'Converted Deal Value', 'Converted Cover',
       'Slippage', 'Spread', 'timebetween', 'timebetween_minutes'],
      dtype='object')

In [51]:
dfnew=df[['Client','RFQStatus','InstrumentSubGroup','Market Traded Vol (USD)','Our Traded Vol',\
          'TiedWonVol','Num of Dealers','Trader','Sales','Covered Vol','ActionStr','Tier','Market','RFQNumberOfQuotes',\
          'Buy/Sell','First Response Time (Sec)','TradeSizeBucket','Sector',"timebetween","Slippage"]]

In [61]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

def one_hot_encode_sklearn(df):
    # Identify categorical columns based on dtype or unique values
    categorical_columns = [col for col in df.columns if df[col].dtype == 'object' or df[col].nunique() < 10]

    # Initialize OneHotEncoder
    encoder = OneHotEncoder(sparse_output=False, drop=None)  # Set drop='first' to avoid multicollinearity

    # Fit and transform only categorical columns
    encoded_data = encoder.fit_transform(df[categorical_columns])

    # Create DataFrame with encoded columns
    encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_columns))

    # Drop original categorical columns and concatenate encoded ones
    df_encoded = pd.concat([df.drop(columns=categorical_columns), encoded_df], axis=1)
    return df_encoded

# Apply the function
df_encoded = one_hot_encode_sklearn(dfnew)
df_encoded['Slippage'] = df['Slippage']

In [63]:
from sklearn.preprocessing import MinMaxScaler
df_cleaned = df_encoded.dropna()
scaler = MinMaxScaler()
df_normalized = pd.DataFrame(scaler.fit_transform(df_cleaned), columns=df_cleaned.columns)

In [66]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Define features and target variable
X = df_normalized.drop(columns=['Slippage'])  # Independent variables
y = df_normalized['Slippage']  # Dependent variable

# Split the data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Linear Regression model
model = LinearRegression()

# Fit the model with training data
model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 1817529680010.333
R-squared: -1.3816161227403459e+19

In [78]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor  # For regression
from sklearn.metrics import mean_squared_error, r2_score


# Initialize the Random Forest Regressor model
rf_model = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)

# Fit the model with training data
rf_model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = rf_model.predict(X_test)

In [81]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 4.053341232703954e-05
R-squared: -307.1194029271738

In [102]:

# Get feature importance
feature_importances = rf_model.feature_importances_
feature_names = X.columns

importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})
# Sort the features by importance in descending order
importance_df = importance_df.sort_values(by='Importance', ascending=False)

In [106]:
import pandas as pd
import plotly.express as px

# Step 1: Create a DataFrame with the provided data
data = {
    'Feature': ['Market Traded Vol (USD)', 'Covered Vol', 'Client_Client40', 
                'First Response Time (Sec)', 'Trader_Trader7', 'Sales_Sale7',
                'Num of Dealers', 'ActionStr_TradedAway', 'Client_Client33',
                'RFQNumberOfQuotes', 'InstrumentSubGroup_UNKNOWN', 
                'InstrumentSubGroup_ONTHERUN', 'Sales_Sale2', 'Sector_15-30 YR',
                'Trader_Trader6', 'TradeSizeBucket_50+M', 'Sales_Sale4'],
    'Importance': [0.433863, 0.158960, 0.095088, 0.029459, 0.027125, 0.025567,
                   0.018539, 0.018432, 0.013647, 0.013474, 0.013367, 
                   0.011669, 0.011663, 0.011016, 0.010676, 0.010073, 0.009997]
}

# Create a DataFrame
importance_df = pd.DataFrame(data)

# Sort the DataFrame by Importance in descending order
importance_df = importance_df.sort_values(by='Importance', ascending=False)

In [107]:
# Step 2: Create an interactive bar chart using Plotly
fig = px.bar(importance_df, x='Importance', y='Feature',
             title="Feature Importance in Model",
             labels={'Importance': 'Importance', 'Feature': 'Features'},
             orientation='h',  # Horizontal bar chart for better readability
             color='Importance',  # Color by importance for emphasis
             color_continuous_scale='Viridis',  # Choose a visually appealing color scale
             template='plotly_white')

# Customize layout for better aesthetics
fig.update_layout(
    title_font=dict(size=20, family='Arial'),
    xaxis_title="Importance",
    yaxis_title="",
    xaxis=dict(showgrid=False),
    yaxis=dict(showgrid=False, categoryorder='total ascending'),
    plot_bgcolor='rgba(0,0,0,0)',
    hoverlabel=dict(font_size=12),
)

# Add annotations for better clarity (optional)
for i, row in importance_df.iterrows():
    if row['Importance'] > 0:  # Only annotate non-zero importance
        fig.add_annotation(
            x=row['Importance'],
            y=row['Feature'],
            text=f"{row['Importance']:.2f}",
            showarrow=False,
            font=dict(size=12),
            align="right"
        )

# Show the interactive plot
fig.show()